version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
    networks:
      - local
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - local

networks:
  local:
    driver: bridge
