version: "3.8"

services:
  php:
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
      args:
          - GITHUB_TOKEN=${GITHUB_TOKEN}
    container_name: ${APP_NAME}_php
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_PORT=${APP_PORT}
    volumes:
      - ./:/var/www/html
      - php-vendor:/var/www/html/vendor
    networks:
      - network_bridge
    depends_on:
      - database

  node:
    build:
      context: ./
      dockerfile: .docker/node/Dockerfile
    container_name: ${APP_NAME}_node
    ports:
      - "5174:5174"
    volumes:
      - ./:/app
      - node-modules:/app/node_modules
    tty: true
    networks:
      - network_bridge

  database:
    image: mariadb:10.5
    container_name: ${APP_NAME}_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - network_bridge

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${APP_NAME}_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database
    networks:
      - network_bridge

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ${APP_NAME}_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
        - "5672:5672"
        - "15672:15672"
    networks:
        - network_bridge

networks:
  network_bridge:
    driver: bridge

volumes:
  db-data:
  php-vendor:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./vendor
  node-modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules